language : python
before_install:
- chmod +x manage.py
python:
- "3.6"
install: "pip install -r requirements.txt"
script:
- SECRET_KEY="something" ./manage.py test
after_success:
    - bash <(curl -s https://codecov.io/bash)